import * as anchor from "@coral-xyz/anchor";
import { BN, Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair } from "@solana/web3.js";
import { Reviewsdotfun } from "../target/types/reviewsdotfun";
import IDL from "../target/idl/reviewsdotfun.json";
import { BankrunProvider } from "anchor-bankrun";
import { startAnchor, BanksClient, ProgramTestContext } from "solana-bankrun";

describe("reviewsdotfun", () => {
  let admin: Keypair;
  let globalPda: PublicKey;
  let program: Program<Reviewsdotfun>;
  let provider: BankrunProvider;
  let context: ProgramTestContext;
  let banksClient: BanksClient;

  beforeAll(async () => {
    context = await startAnchor(
      "",
      [{ name: "reviewsdotfun", programId: new PublicKey(IDL.address) }],
      [
        // accounts field, accounts other than the provider.wallet.payer
      ],
    );
    provider = new BankrunProvider(context);
    anchor.setProvider(provider);
    program = new Program<Reviewsdotfun>(IDL as Reviewsdotfun, provider);
    banksClient = context.banksClient;
    admin = provider.wallet.payer; // auto generated by provider, also the signer of TXs

    [globalPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("global")],
      program.programId,
    );
  });

  it("Init global pda", async () => {
    const feeVault = new anchor.web3.Keypair();
    const authority = new anchor.web3.Keypair();

    await program.methods
      .initGlobal({
        feeVault: feeVault.publicKey,
        authority: authority.publicKey,
      })
      .accounts({})
      .rpc();

    const globalPdaData = await program.account.global.fetch(
      globalPda,
      "confirmed",
    );
    console.log(globalPdaData);
  });
});
